routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\ContactController;
use App\Http\Controllers\ArticleController;
use App\Http\Controllers\ParserController;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])
->name('home');

Route::get('/', function () {
  return view('home');
})->name('index');

Route::get('/parser', function () {
  return view('parser');
})->middleware('auth')->name('parser');

Route::post('/parser', [ParserController::class, 'store'])->name('parser-post');

Route::get('/contact', function () {
    return view('contact');
})->name('contact');

Route::get('/feedback/all/{id}', [ContactController::class, 'showOneMessage'])
->name('showOneMessage');

Route::get('/feedback/all', [ContactController::class, 'allData'])
->name('feedback');

Route::post('/feedback', [ContactController::class, 'submit'])->name('feedback-form');

//русурсная маршрутизация
Route::resource('/articles', ArticleController::class);

app/Models/Article.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Article extends Model
{
    use HasFactory;
    //автоматическое преобразование Json в массив для полей с ссылками на изображения
    protected $casts = [
       'smallImage' => 'array',
       'bigImage' => 'array',
       'price' => 'integer'
    ];
    protected $dates = [
        'updateDate',
    ];
    protected $fillable = ['articleID', 'title', 'smallImage', 'price', 'bigImage', 'text', 'phone', 'updateDate', 'area'];


}

app/Http/Controllers/ArticleController.php
<?php

namespace App\Http\Controllers;

use App\Models\Article;
use Illuminate\Http\Request;
use DateTime;
class ArticleController extends Controller
{
  /**
  * Display a listing of the resource.
  *
  * @return \Illuminate\Http\Response
  */
  public function index(Request $request)
  {
    //получение GET параметров из формы фильтра объявлений
    $minPrice = (int)$request->input('minPrice');
    $maxPrice = (int)$request->input('maxPrice');
    $addDays = $request->input('addedDate');

    //сортировка по дате
    $curentDate = date("Y-m-d H:i:s");
    if(!empty($addDays)) {
      $objCurentDate = new DateTime($curentDate);
      $objCurentDate->modify("-{$addDays} day");
      $dateQuery = $objCurentDate->format("Y-m-d H:i:s");
      $addDays = $dateQuery;
    }

    $articles = Article::when($minPrice, function ($query, $minPrice) { //сработает если первый параметр true
      return $query->where('price', '>', $minPrice);
    })
    ->when($maxPrice, function ($query, $maxPrice) {
      return $query->where('price', '<', $maxPrice);
    })
    ->when($addDays, function ($query, $addDays) {
      return $query->whereDate('updateDate', '>', $addDays);
    })
    ->orderByDesc('id')
    ->Simplepaginate(21); //выбор всех объявлений с простой пагинацией
    // compact('articles') => [ 'articles' => $articles ]

    return view('article.index', compact('articles'));
  }

  /**
  * Show the form for creating a new resource.
  *
  * @return \Illuminate\Http\Response
  */

  public function create()
  {
    $article = new Article();

    return view('article.create', compact('article'));
  }

  /**
  * Store a newly created resource in storage.
  *
  * @param  \Illuminate\Http\Request  $request
  * @return \Illuminate\Http\Response
  */

  public function store(Request $request)
  {
    // Проверка введённых данных
    // Если будут ошибки, то возникнет исключение
    // Иначе возвращаются данные формы
    $data = $this->validate($request, [
      'title' => 'required',
      'price' => 'required',
      'phone' => 'required',
      'text' => 'required|min:10',
    ]);

    $article = new Article();
    // Заполнение статьи данными из формы
    $article->fill($data);
    $article->updateDate = date("Y-m-d H:i:s");
    $article->smallImage = [''];
    $article->bigImage = [''];
    // При ошибках сохранения возникнет исключение
    $article->save();

    // Редирект на указанный маршрут с добавлением флеш-сообщения
    $request->session()->flash('status', 'Объявление добавлено!');
    return redirect()->route('articles.create');
  }

  /**
  * Display the specified resource.
  *
  * @param  \App\Models\Article  $article
  * @return \Illuminate\Http\Response
  */
  public function show(Article $article)
  {
    return view('article.show', compact('article'));
  }

  /**
  * Show the form for editing the specified resource.
  *
  * @param  \App\Models\Article  $article
  * @return \Illuminate\Http\Response
  */
  public function edit(Article $article)
  {
    return view('article.edit', compact('article'));
  }

  /**
  * Update the specified resource in storage.
  *
  * @param  \Illuminate\Http\Request  $request
  * @param  \App\Models\Article  $article
  * @return \Illuminate\Http\Response
  */
  public function update(Request $request, Article $article)
  {
    $data = $this->validate($request, [
      // У обновления немного изменённая валидация. В проверку уникальности добавляется название поля и id текущего объекта
      // Если этого не сделать, Laravel будет ругаться на то что имя уже существует
      'title' => 'required|min:5',
      'price' => 'required',
      'phone' => 'required',
      'text' => 'required|min:10',
    ]);

    $article->fill($data);
    $article->save();
    $request->session()->flash('status', 'Объявление обновлено!');
    return redirect()->route('articles.index');
  }

  /**
  * Remove the specified resource from storage.
  *
  * @param  \App\Models\Article  $article
  * @return \Illuminate\Http\Response
  */
  public function destroy(Request $request, Article $article)
  {
    //удаление в шаблонах с использованием @rails/ujs
    $article->delete();
    $request->session()->flash('status', 'Объявление удалено!');
    return redirect()->route('articles.index');
  }
}

resources/views/article/create.blade.php
@extends('layouts.app')

@section('content')
<h3>Создать объявление</h3>

{{ Form::model($article, ['url' => route('articles.store')]) }}

  @include('article.form')
  {{ Form::submit('Создать', ['class' => 'btn btn-primary']) }}
{{ Form::close() }}
@endsection

resources/views/article/edit.blade.php
@extends('layouts.app')

@section('content')
<h3>Исправить объявление</h3>

{{ Form::model($article, ['url' => route('articles.update', $article), 'method' => 'PATCH']) }}
  @include('article.form')
  {{ Form::submit('Обновить', ['class' => 'btn btn-primary']) }}
{{ Form::close() }}
@endsection

resources/views/article/form.blade.php
@if (Session::has('status'))
	{{ Session::get('status') }}
@endif
<div class="form-group">
    {{ Form::label('title', 'Заголовок') }}
    {{ Form::text('title', null, ['class' => 'form-control']) }}

    {{ Form::label('price', 'Цена') }}
    {{ Form::text('price', null, ['class' => 'form-control']) }}

		{{ Form::label('phone', 'Телефон') }}
    {{ Form::text('phone', null, ['class' => 'form-control']) }}

    {{ Form::label('text', 'Описание') }}
    {{ Form::textarea('text', null, ['class' => 'form-control', 'rows' => '5']) }}
</form>

resources/views/article/index.blade.php
@extends('/layouts.app')

@section('title', 'Главная')

@section('content')

<div class="row">
  <div class="col-3">
    @include('inc.aside')
  </div>
  <div class="col-9">
    <div class="class="album py-5 bg-light"">
      <div class="row">
        @foreach ($articles as $article)
        <div class="col-md-4">
          <div class="card mb-4 shadow-sm">
            <?php //если нет изображений
            $titleImage = $article->smallImage[0] ?? '';
            ?>
            <img src="<?= $titleImage ?>" alt="">
            <div class="card-body">
              <p class="card-text">
                <h6><a href="{{ route('articles.show', $article->id) }}">{{$article->title}}</a></h6>
              </p>
              <?php //если цена не указана
              if($article->price == 0) {
                $price = "Цена договорная";
              } else  {
                $price = $article->price."$";
              }
              ?>
              <p>Цена: <?= $price ?></p>
              <p>Дата обновления: {{$article->updateDate->format('d.m.Y') }}</p>
              <div class="d-flex justify-content-between align-items-center">
                <div class="btn-group">
                  <a  href="{{ route('articles.show', $article) }}">
                    <button  class="btn btn-primary" type="button" name="button">
                      Подробнее
                    </button>
                  </a>
                  &nbsp
                  @auth
                    <a href="{{ route('articles.destroy', $article) }}"
                    data-method="delete"
                    rel="nofollow">
                    <button  class="btn btn-primary" type="button" name="button">
                      Удалить
                    </button>
                    </a>
                  @endauth
              </div>
            </div>
          </div>
        </div>
      </div>
      @endforeach
    </div>
  </div>
  <div class="pagination pagination-lg justify-content-center">
    {{ $articles->links() }}
  </div>
</div>

@endsection

resources/views/article/show.blade.php
@extends('layouts.app')

@section('content')
<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
  <h1>{{$article->title}}</h1>
  <div class="class="album py-5 bg-light"">
    <div class="row">
      @foreach ($article->smallImage as $key => $linkSmallImage)
      <div class="col-md-4">
        <div class="card mb-4 shadow-sm">
          <a href="{{$article->bigImage[$key]}}">
          <img src="{{$linkSmallImage}}" alt="" style="width:100%">
          </a>
        </div>
      </div>
      @endforeach
    </div>
  </div>
  <p class="lead">{{$article->text}}</p>

</div>
<div class="">
  <p>Площадь участка: {{$article->area}}</p>
  <p>Дата обновления: {{$article->updateDate->format('d.m.Y') }}</p>
  <?php
  if($article->price == 0) {
    $price = "Цена договорная";
  } else  {
    $price = $article->price."$.";
  }
   ?>
  <p>Цена: <?= $price ?></p>

  <p>Телефон: {{$article->phone}}</p>
  <a  href="{{ route('articles.edit', $article->id) }}">
    <button  class="btn btn-primary" type="button" name="button">
      Редактировать
    </button>
  </a>
</div>

@endsection