routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\ContactController;
use App\Http\Controllers\ArticleController;
use App\Http\Controllers\ParserController;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])
->name('home');

Route::get('/', function () {
  return view('home');
})->name('index');

Route::get('/parser', function () {
  return view('parser');
})->middleware('auth')->name('parser');

Route::post('/parser', [ParserController::class, 'store'])->name('parser-post');

Route::get('/contact', function () {
    return view('contact');
})->name('contact');

Route::get('/feedback/all/{id}', [ContactController::class, 'showOneMessage'])
->name('showOneMessage');

Route::get('/feedback/all', [ContactController::class, 'allData'])
->name('feedback');

Route::post('/feedback', [ContactController::class, 'submit'])->name('feedback-form');

//русурсная маршрутизация
Route::resource('/articles', ArticleController::class);

resources/views/inc/aside.blade.php
<aside class="aside">
  <h4>Параметры поиска:</h4>
  <form class="" action="/articles" method="GET">
    @csrf
    <div class="form-group">
      <p>Цена</p>
      <label for="minPrice">от</label>
      <input type="text" name="minPrice" id="minPrice" value="" placeholder="" class="form-control">
      <label for="maxPrice">до</label>
      <input type="text" name="maxPrice" id="maxPrice" value="" placeholder="" class="form-control">

    </div>

    <div class="form-group">
      <p>Дата добавления</p>
      <input type="radio" id="today" name="addedDate" value="1">
      <label for="today">за сегодня</label><br>
      <input type="radio" id="3day" name="addedDate" value="3">
      <label for="all">за последние 3 дня</label><br>
      <input type="radio" id="week" name="addedDate" value="7">
      <label for="week">за неделю</label><br>
      <input type="radio" id="month" name="addedDate" value="30">
      <label for="month">за месяц</label>
    </div>

    <button type="submit" name="button" class="btn btn-primary">Поиск</button>
  </form>
  <br>
  @auth
  <a  href="{{route('articles.create')}}"><button  class="btn btn-primary" type="button" name="button">
    Добавить объявление
  </button></a>
  @endauth
</aside>

resources/views/inc/content.blade.php
<div class="container">
  <div class="card-deck mb-3 text-center">
    <div class="card mb-4 shadow-sm">
      <div class="card-header">
        <h4 class="my-0 font-weight-normal">Free</h4>
      </div>
      <div class="card-body">
        <h1 class="card-title pricing-card-title">$0 <small class="text-muted">/ mo</small></h1>
        <ul class="list-unstyled mt-3 mb-4">
          <li>10 users included</li>
          <li>2 GB of storage</li>
          <li>Email support</li>
          <li>Help center access</li>
        </ul>
        <button type="button" class="btn btn-lg btn-block btn-outline-primary">Sign up for free</button>
      </div>
    </div>
    <div class="card mb-4 shadow-sm">
      <div class="card-header">
        <h4 class="my-0 font-weight-normal">Pro</h4>
      </div>
      <div class="card-body">
        <h1 class="card-title pricing-card-title">$15 <small class="text-muted">/ mo</small></h1>
        <ul class="list-unstyled mt-3 mb-4">
          <li>20 users included</li>
          <li>10 GB of storage</li>
          <li>Priority email support</li>
          <li>Help center access</li>
        </ul>
        <button type="button" class="btn btn-lg btn-block btn-primary">Get started</button>
      </div>
    </div>
    <div class="card mb-4 shadow-sm">
      <div class="card-header">
        <h4 class="my-0 font-weight-normal">Enterprise</h4>
      </div>
      <div class="card-body">
        <h1 class="card-title pricing-card-title">$29 <small class="text-muted">/ mo</small></h1>
        <ul class="list-unstyled mt-3 mb-4">
          <li>30 users included</li>
          <li>15 GB of storage</li>
          <li>Phone and email support</li>
          <li>Help center access</li>
        </ul>
        <button type="button" class="btn btn-lg btn-block btn-primary">Contact us</button>
      </div>
    </div>
  </div>

resources/views/inc/footer.blade.php
  <footer class="pt-6 my-md-5 pt-md-5 border-top text-right">
    <div class="footer">
      <small class="d-block mb-3 text-muted">©2020 Andrew Proz</small>
    </div>
  </footer>
</div>

resources/views/inc/messages.blade.php
<!-- Для вывода ошибок и сообщений -->
@if($errors->any())
<div class="alert alert-danger">
  <ul>
    @foreach($errors->all() as $error)
      <li>{{ $error }}</li>
    @endforeach
  </ul>

</div>
@endif

@if(session('succes'))
  <div class="alert alert-success">
    {{ session('succes')}}

  </div>
@endif

@if (Session::has('status'))
  <div class="alert alert-success">
	   {{ Session::get('status') }}
  </div>
@endif

resources/views/inc/nav.blade.php
<div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-white border-bottom shadow-sm">
  <img src="/favicon.ico" alt="Houses">
  <h5 class="my-0 mr-md-auto font-weight-normal">&nbsp Домовик</h5>
  <nav class="my-2 my-md-0 mr-md-3">
    <a class="p-2 text-dark" href="{{route('index')}}">Главная</a>
    <a class="p-2 text-dark" href="/articles">Объявления</a>
    <a class="p-2 text-dark" href="{{route('contact')}}">Контакты</a>
    <a class="p-2 text-dark" href="{{route('feedback')}}">Отзывы</a>
  @auth
    <a class="p-2 text-dark" href="{{route('parser')}}">Панель управления</a>
  @endauth

  </nav>


      <!-- Authentication Links -->
      @guest

              <a class="btn btn-outline-primary" href="{{ route('login') }}">{{ __('Login') }}</a>

          @if (Route::has('register'))

                  <a class="btn btn-outline-primary" href="{{ route('register') }}">{{ __('Register') }}</a>

          @endif
      @else

              <a id="navbarDropdown" class="btn btn-outline-primary dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                  {{ Auth::user()->name }}
              </a>

              <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                  <a class="dropdown-item" href="{{ route('logout') }}"
                     onclick="event.preventDefault();
                                   document.getElementById('logout-form').submit();">
                      {{ __('Logout') }}
                  </a>

                  <form id="logout-form" action="{{ route('logout') }}" method="POST" class="d-none">
                      @csrf
                  </form>
              </div>

      @endguest


  <!-- <a class="btn btn-outline-primary" href="#">Регистрация</a> -->
</div>